### ISSUE TITLE
Accept alternate data format

### ISSUE THREAD

**Issue by yegle** [mkaz/termgraph#1]
It'll be great if `termgraph` can accept reading input from stdin from `uniq -c` result.

**Comment by Aquassaut** [comment]
Just a quick note:
You can already do that with some command line magic, specifically process substitution. Just try:

> termgraph.py <(echo -e 'two two three three three'|sed 's/ /\n/g'|uniq -c| awk '{ print $2 " " $1; }')

You should see something like:

```
------------------------------------
Reading data from /dev/fd/63
------------------------------------

two  : ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   2.00
three: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇   3.00

```

Stdin support would be more elegant, and is very easy to implement (check pull request #3 ).

As far as format goes, since you can construct it with standard UNIX tools (such as awk in my example), I think there is value in keeping it as simple as possible.

**Comment by mkaz** [comment]
PR #3 was merged which closes this one.
